services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    pull_policy: never
    volumes:
      - mdb_vol:/var/lib/mysql
    networks:
      - best_network
    ports:
      - "3306:3306"
    env_file:
      - .env
    restart: always

  nginx: 
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    pull_policy: never
    volumes:
      - wp_vol:/var/www/html
    networks:
      - best_network
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always
  
  wordpress:
    container_name: wordpress
    image: wordpress
    pull_policy: never
    build: ./requirements/wordpress
    networks:
      - best_network
    volumes:
      - wp_vol:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always

networks:
  best_network:

volumes:
  mdb_vol:
    name: mdb_vol
    driver: local
    driver_opts:
      type: none
      device: /home/aolde-mo/data/mdb_vol
      o: bind
  wp_vol:
    name: wp_vol
    driver: local
    driver_opts:
      type: none
      device: /home/aolde-mo/data/wp_vol
      o: bind